### ISSUE TITLE
[Configurator] :: Public Key inputted for SSHConsole ignored

### ISSUE THREAD

**Issue by jsimmonds2** [FarmBot/farmbot_os#1029]
Refer to [this FarmBot Forum post](https://forum.farmbot.org/t/using-farmbotos-beta-updates/3951/59)

FarmbotOS developers may not see this bug because their builds can see their own **`id_rsa.pub`** key !

P.s.  **`Question`** : Do I need a current Fork of the `farmbot_os.git` repo to create a Pull Request on ?

**Comment by jsimmonds2** [comment]
@ConnorRigby , thanks.  I'll submit a little PR with a fix, because, existing SSHConsole works just fine for my needs.

> complete it, and have not had time.

Hasn't Rory tried over-clocking you yet ? :):)

**Comment by ConnorRigby** [comment]
Closed via #1030
