### ISSUE TITLE
[Bug] no compiler for home

### ISSUE THREAD

**Issue by jsimmonds2** [FarmBot/farmbot_os#1034]
# Expected Behavior
On Controls page, press Home button (house icon)
No error occurs and bot homes correctly

# Actual Behavior
On FarmbotOS Console, a Runtime error is logged.  I don't have a real bot but I imagine nothing moved.

# Steps to Reproduce
Install latest FarmbotOS Release from **`.IMG`** downloaded from GH ( **`v8.1.0`** at **`4b12dfaf`** ) and use **`my.farm.bot`**  WebApp Release ( says **`VERSION: FCE9ACD7`** )

# Results of `git log -1`

Run `git log -1` and paste the results here.
**`n/a`**

Picture this :)

![image](https://user-images.githubusercontent.com/1224439/67364823-0949d080-f5bc-11e9-93bf-63602afc8076.png)

**Comment by ConnorRigby** [comment]
Thanks @jsimmonds2. Pushing a fix right now

**Comment by ConnorRigby** [comment]
Fixed with 29bff5750110cab60701d22c84d32a5785f5da3f
