### ISSUE TITLE
[Bug] Can't enable Firmware Debug log

### ISSUE THREAD

**Issue by jsimmonds2** [FarmBot/farmbot_os#1056]
Testing on Pre-Release **`v8.3.0-rc3`**

Expected `fbos_config.firmware_debug_log` to change as the FE Log Setting item was toggled.

Picture this :)

![image](https://user-images.githubusercontent.com/1224439/68453543-f2f17500-0249-11ea-9766-c506a49dacc7.png)

**Comment by gabrielburnworth** [comment]
Try `fbos_config.arduino_debug_messages`.

**Comment by jsimmonds2** [comment]
Oh, Ok and **thanks**. 
Sorry for the noise.

Some refactoring going on that I hadn't bothered to follow through :(

**Comment by jsimmonds2** [comment]
A deeper look tells me that bug(s) lurk.

E.g [https://github.com/FarmBot/farmbot_os/blob/staging/farmbot_core/lib/farmbot_core/firmware_side_effects.ex](https://github.com/FarmBot/farmbot_os/blob/staging/farmbot_core/lib/farmbot_core/firmware_side_effects.ex#L155)
```
  should_log? = Asset.fbos_config().firmware_debug_log
```
:-)

**Comment by ConnorRigby** [comment]
I've noticed a bug lately where I have to refresh the page  too make that panel work

**Comment by jsimmonds2** [comment]
Yes, same. That toggle slider seems to have some busy code underneath it !

**Comment by jsimmonds2** [comment]
Finally **got** my Firmware Debug logs :)

* Built a **`farmduino_k14.hex`** with debug logging enabled.
* Forced **`firmware_debug_log`** to true in **`FbosConfig`** using
```
FarmbotCore.Asset.Private.mark_dirty! FarmbotCore.Asset.fbos_config(), %{firmware_debug_log: true}

```
Surely **`arduino_debug_messages`** is now/nearly obsolete ?

**Comment by ConnorRigby** [comment]
i believe `arduino_debug_messages` and `firmware_debug_log` are the same thing. There may be a bug where `botstate.arduino_debug_messages` is not updated when `firmware_debug_log` is updated and vice versa.

**Comment by ConnorRigby** [comment]
oh actually, i see that both of those values are real values, not one as a mirror of the other. i'll have to cross reference which one is **supposed** to be used for this feature.
