### ISSUE TITLE
[CeleryScript] Resources aren't updated after `resource_update`

### ISSUE THREAD

**Issue by gabrielburnworth** [FarmBot/farmbot_os#1067]
# Mount tool
## CeleryScript
```
{
  "kind": "resource_update",
  "args": {
    "value": 12345,
    "label": "mounted_tool_id",
    "resource_type": "Device",
    "resource_id": 0
  },
  "body": [],
}
```

## Result
Device resource:
```
{
  mounted_tool_id: null
}
```

## Relevant code
https://github.com/FarmBot/farmbot_os/blob/e6bd215039e680f04ec30c3091186fbe95d3e689/farmbot_os/lib/farmbot_os/sys_calls/resource_update.ex#L7-L13

# Update plant stage
## CeleryScript
```
{
  "kind": "resource_update",
  "args": {
    "value": "harvested",
    "label": "plant_stage",
    "resource_type": "Plant",
    "resource_id": 98765
  },
  "body": [],
}
```

## Result
Plant resource:
```
{
  plant_stage: "planned"
}
```

## Relevant code
https://github.com/FarmBot/farmbot_os/blob/e6bd215039e680f04ec30c3091186fbe95d3e689/farmbot_os/lib/farmbot_os/sys_calls/resource_update.ex#L15-L24

# Remove point
## CeleryScript
```
{
  "kind": "resource_update",
  "args": {
    "resource_id": 45678,
    "resource_type": "GenericPointer",
    "label": "discarded_at",
    "value": "{{ Time.now }}"
  },
  "body": [],
}
```

# Result
Error:
```
{
  "kind": "explanation", 
  "args": {
    "message": "Unknown resource: GenericPointer.45678\n"
  }
}
```

## Relevant code
https://github.com/FarmBot/farmbot_os/blob/staging/farmbot_os/lib/farmbot_os/sys_calls/resource_update.ex

**Comment by ConnorRigby** [comment]
## Mount tool
Farmbot doesn't currently track `device.mounted_tool_id`. This will need a migration, but should be easy.

## Update plant stage
this one worked for me. The caveat is that it isn't immediately available in the API. It could take up to 10 seconds for the HTTP request to  complete.

## Remove point
* Farmbot doesn't allow modification of `GenericPointer` currently. It can be added easily.
* `{{ Time.now() }}` will not work and i don't really want to add support for that. I think we should come up with a different solution for that. This should get it's own feature request
