### ISSUE TITLE
Incorrect units in Firmware Parameter log message

### ISSUE THREAD

**Issue by jsimmonds2** [FarmBot/farmbot_os#1074]
Changing MAX SPEED (MM/S) for X, Y or Z axis results in a Log Message which append units as **`(steps/mm)`**.  Surely that's not a unit of speed ?
 
Picture this :)

![image](https://user-images.githubusercontent.com/1224439/69831720-cba52b00-127e-11ea-843d-3bb127c52ce9.png)

**Comment by ConnorRigby** [comment]
This log actually is correct. The app does calculations based on the value stored in `steps per mm` to convert the data to `mm per second`. So the user inputs `100 mm / s` and farmbot receives `55 steps per second`

**Comment by jsimmonds2** [comment]
Understand about that calculation, just that there is a **different** control for STEPS PER MM.

> and farmbot receives `55 steps per second`

That would be 550 and as you said, the unit really is **steps per second**  :)
