### ISSUE TITLE
[bug] CI commit hash not found on GH ?

### ISSUE THREAD

**Issue by jsimmonds2** [FarmBot/farmbot_os#1110]
I love traceability in software changes.

Probably my myopia, but for FBOS **v9.0.2** from the CI artefacts, the commit hash can't be found in the GH **farmbot_os** repo. (?)

Here is the CI **.IMG** running right now ( 5a95d6c3 ).
I can't see that commit on GitHub.  ( help me :)

![image](https://user-images.githubusercontent.com/1224439/72131103-67be6800-33cf-11ea-9b2d-73d839669581.png)

**Comment by RickCarlino** [comment]
@jsimmonds2 Can you try again- I am seeing it on Github fine right now. Maybe it was related to those CDN hiccups you mentioned last night?

**Comment by jsimmonds2** [comment]
Thanks @RickCarlino  !  User-error ( mine ). Seems I need to check the **master** branch for CI builds :)
