### ISSUE TITLE
[bug, cosmetic] unhandled message in error state: after Farmware exits normally

### ISSUE THREAD

**Issue by jsimmonds2** [FarmBot/farmbot_os#1180]
Picture this :)  (near bottom of image)

![image](https://user-images.githubusercontent.com/1224439/77602658-17808c00-6f62-11ea-9c3d-98e5f2f1eaf0.png)

**Comment by RickCarlino** [comment]
Interesting find @jsimmonds2 thanks for bringing it to our attention. I will take a look next time I'm in there.

**Comment by jsimmonds2** [comment]
@RickCarlino 
This warning has quietly vanished in **v9.2.2** . . will close as I can't reproduce it by either running a Farmware from a Sequence or just using the RUN button on the Farmware web app page.

**Comment by RickCarlino** [comment]
@jsimmonds2 That sounds right. I made some fixes for the users that were hitting "Can't perform X in state Y" errors, and it very well could be that the fix in the firmware handler corrected unnoticed problems elsewhere.

**Comment by jsimmonds2** [comment]
Hmmm .. it's back . . I'll try and hunt down more relevant detail / evidence !

Using **v9.2.2** in **dev** env plus custom **farmbot_system_rpi3** which supports **crash.dump** file creation.

![image](https://user-images.githubusercontent.com/1224439/79983826-a5ad4b00-84eb-11ea-9afc-22843f41f652.png)

**Comment by RickCarlino** [comment]
@jsimmonds2 Thanks for investigating this.

RE: Nerves System updates - It's still on my TODO list (See! I even took a screenshot of the Trello card! :sweat_smile:) but I've been putting it off until things are a bit more stable. Right now ~10% of customers are hitting failed OTAs and we still have not isolated the root cause, making me hesitant to change the platform until a root cause is isolated.

![image](https://user-images.githubusercontent.com/1388608/79994754-f7b68800-847b-11ea-9542-b25c1842fd7b.png)

I will keep you posted.

**Comment by jsimmonds2** [comment]
* making me hesitant to change the platform until a root cause is isolated.

Absolutely !  For me there's **no rush** at all to have crash dumps officially enabled, since I managed to build a local **farmbot_system_rpi3** with that flag.

What I'm doing with that is trying to come up with a change that permits more FarmEvents without using so much heap.

The crashes I'm getting with 8_000 or more FarmEvents are usually due to the **FarmbotCeleryScript.Scheduler** process **Garbing** . . likely due to the huge amount of heap churn caused by the large amount of stuff changing in **state**.
I'm thinking an `ordered_set` inside an **ets** table is the way to store these things (?)

**Comment by RickCarlino** [comment]
Ah interesting. I am not too familiar with those internals yet, but your theory makes sense. Scheduling FarmEvents has historically been very resource intensive.

**Comment by jsimmonds2** [comment]
Hello @RickCarlino 

This one is like a fly racing room to room in a house . . it won't go away :-)

**FBOS v10.1.0-rc1**

![image](https://user-images.githubusercontent.com/1224439/83251432-e97f2880-a1ec-11ea-82c3-c845c8803085.png)
