### ISSUE TITLE
Unused variable warning is polluting the Serial Console :)  10.1.3

### ISSUE THREAD

**Issue by jsimmonds2** [FarmBot/farmbot_os#1225]
![image](https://user-images.githubusercontent.com/1224439/88473504-8e09b680-cf61-11ea-861b-e5aad1005688.png)

**Comment by RickCarlino** [comment]
I take the blame for this one @jsimmonds2 . While implementing the filter groups / group iteration feature, I was having issues with a part of the CSVM and worked around it temporarily. Definitely a bug, but the warning does not point to a significant problem, rather it points to some corner cutting on my part. I hope I can fix this in the upcoming v3 MOVE TO block.

**Comment by jsimmonds2** [comment]
> the blame
"blame" . . What's _that_ ? :-)

Can CircleCI catch the real **stderr** stream ? Or **compile time** warnings like this ?

**Comment by RickCarlino** [comment]
:stuck_out_tongue: I need to do a patch release today anyway to un-bork an unrelated issue. I will include a simple fix for this in 10.1.4.

**Comment by jsimmonds2** [comment]
Ooops . . got a New one now ( only on Serial Console **stderr** , not SSH ) 10.1.4 commit **1c5ef14b**

![image](https://user-images.githubusercontent.com/1224439/88615901-2628ac80-d0d6-11ea-939d-16f882378d4b.png)

**Comment by jsimmonds2** [comment]
Hello @RickCarlino ! Has this one ( above ) been cleaned up yet ? :)  Thanks !

**Comment by RickCarlino** [comment]
@jsimmonds2 It's pretty low priority given the other things that are going on this week, but I will need to go in there next week when writing the V3 MOVE block that's coming up.

Did the fix make it worse? I can remove it if that's the case.

**Comment by jsimmonds2** [comment]
Thanks @RickCarlino .  No problems 😅  It's **not** worse after the recent fix, just a **different** unused variable.

Rarely use the Console device, but it's the only way I know of to see the **stdio** and **stderr** streams of the BEAM.

**Comment by RickCarlino** [comment]
@jsimmonds2 Found a fix while working on unrelated features. The fix is in bb077b13 and will be deployed as part of v11.0.0

**Comment by jsimmonds2** [comment]
### 👍
