### ISSUE TITLE
DIdnt see a Doc project, so putting this here.  Hyperlink issue with doc webpage

### ISSUE THREAD

**Issue by jwusch** [FarmBot/farmbot_os#1367]
Hey, apologies if this should be in project for Documentation, but hyperlink under SSH section on

https://developer.farm.bot/v14/Documentation/farmbot-os/gathering-information-at-runtime

is broken.  Has it listed as this:
https://github.com/FarmBot/farmbot_os/blob/staging/docs/SSH.md

getting 404

**Comment by gabrielburnworth** [comment]
Thanks for bringing this to our attention. The developer documentation repository is located at [FarmBot-Docs/farmbot-developers](https://github.com/FarmBot-Docs/farmbot-developers), under the [FarmBot-Docs](https://github.com/FarmBot-Docs) organization.

I've replaced the broken link on the [Gathering Information at Runtime page](https://developer.farm.bot/docs/gathering-information-at-runtime) with the [correct one.](https://github.com/FarmBot/farmbot_os/blob/staging/docs/target_development/consoles/ssh.md).
