### ISSUE TITLE
Broadcom Linux Wireless Driver not initializing properly. 

### ISSUE THREAD

**Issue by mrmadhu** [FarmBot/farmbot_os#186]
Hello 

I'm not sure if this was discussed already, as per the setup instruction when i try to configure my home wifi  details and save by accessing 192.168.24.1, nothing happens after clicking save configuration button, it stays in the initial screen, i tried using the both the .img file 2.0.3 and 2.0.2  both has the same issue.  

Only SSID's that are visible is as following

test_ssid
meep
lawl

it does not show my home wifi SSID when scanning wifi 

Thanks in advance for any help

**Comment by mrmadhu** [comment]
Only SSID's that are visible is as following 

test_ssid
meep
lawl

it does not show my home wifi SSID

**Comment by ConnorRigby** [comment]
ah yeah sorry. those things showing up should never happen on a real Raspberry pi. Im going to push a new release you can try fairly shortly.

**Comment by jokosup** [comment]
any ETA when can we expect the new release?

**Comment by ConnorRigby** [comment]
Your on a pi3 correct?
this release should work: [here](https://github.com/FarmBot/farmbot_os/releases/download/v2.0.5/fw-v2.0.5.img)

**Comment by mrmadhu** [comment]
Sorry, It dosent work, it does not scan and show the home wifi SSID

**Comment by RickCarlino** [comment]
@mrmadhu Can you try opening the [JavaScript console](https://developers.google.com/web/tools/chrome-devtools/console/) and tell me if you see any errors? That might have additional information about what the issue is.

**Comment by RickCarlino** [comment]
Javascript console is `ctrl + shift + J` on Linux and Windows. I forget what the hotkey is on Mac.

**Comment by mrmadhu** [comment]
Please find the attached screen shot 
![farmbot os error](https://cloud.githubusercontent.com/assets/22852245/19518194/79e7a598-9623-11e6-9baa-f87c3d8d2e6b.PNG)

**Comment by jokosup** [comment]
Thanks Rick,

1. I am using ubuntu and windows 7.
2. Ubee cable modem with router
3. no firewall software.

i did try with setting up my firewall protection to low in my router as well.

**Comment by jokosup** [comment]
The wifi sometime work, sometime doesn't.

![1476926637901-1890420170](https://cloud.githubusercontent.com/assets/14942067/19543074/006f6f04-963a-11e6-85c7-605fbe45860c.jpg)

**Comment by ConnorRigby** [comment]
Ah i see. That is actually a common problem so far. It is a power issue. The PI3 requires more power than previous pis. Something to the tune of 2.5 amps

**Comment by mrmadhu** [comment]
hello 
i'm still stuck, with the same problem even after disabling firewall and higher amps power supply 
i'm using a raspberry pi 3 
is there any way to ssh to the farmbot os, if yes which ip address ?
Madhu

**Comment by ConnorRigby** [comment]
There is no ssh into it yet. 
(tho it is a feature we are working on)

But i made it on the latest release be able to plug a mouse and keyboard and use the shell over hdmi. 

What is the amperage of you power supply?

**Comment by jokosup** [comment]
i am using 2.1A usb from the power plug. 

it works fine when i run Raspbian Jessie, but not the farmbot_os. 
what makes farmbot_os needs more power?

**Comment by ConnorRigby** [comment]
Im beginning to think it is not a power issue. 2.1 amps should be enough. I can't reproduce locally so i am going to be testing some things on other peoples environments.

**Comment by ConnorRigby** [comment]
relevant kernel logs: 
```
brcmfmac: brcmf_sdio_drivestrengthinit: No SDIO Drive strength init done for chip 43430 rev 1 pmurev 24
brcmfmac_sdio mmc0:0001:1: Direct firmware load for brcm/brcmfmac4330-sdio.txt failed with error -2
brcmfmac: brcmf_sdio_htclk: HT Avail timeout (1000000): clkctl 0x50
```

**Comment by RickCarlino** [comment]
@jokosup @mrmadhu We're still investigating, but thanks for all the great information so far. It appears to be a driver issue.

**Comment by ConnorRigby** [comment]
@jokosup can you try to boot your pi without a hdmi cable plugged in?

**Comment by jokosup** [comment]
yes, i have tried that. same results.

**Comment by mrmadhu** [comment]
Same result  for me as well

**Comment by ConnorRigby** [comment]
@jokosup and @mrmadhu 

can you guys please try flashing the pre-release for me? 
[get it here](https://github.com/FarmBot/farmbot_os/releases/tag/v2.0.7-alpha)
Try it with and without HDMI plugged in.

**Comment by mrmadhu** [comment]
Hi 
just tried, its able to connect to home wifi and gets an IP 

but no luck with my.farmbot.io connectivity or no way to login to the OS, via SSH 

Madhu

**Comment by ConnorRigby** [comment]
@mrmadhu have you created an account on my.farmbot.io first?

**Comment by mrmadhu** [comment]
yes and the id was configured as on the wificonfigurator page

**Comment by ConnorRigby** [comment]
can you try creating an account on [http://staging.farmbot.io](http://staging.farmbot.io) and using those same credentials on configurator?

**Comment by mrmadhu** [comment]
do i need to re-image the sd card again ?

**Comment by ConnorRigby** [comment]
If wifi configurator comes up you dont, but if its 'bricked' then you will

**Comment by mrmadhu** [comment]
@ConnorRigby it connects to staging and gets a message that "BOT status OK , but no control of stepper

**Comment by jokosup** [comment]
I am able to connect to the FarmbotConfigurator, but when i click Save Configuration, it got the "TRYING TO LOGIN" response.  then lost the WiFi. 
i deleted the files from AppData and restart it again, WiFi came back.

**Comment by mrmadhu** [comment]
@ConnorRigby , still stuck, i'm able to shutdown pi from the web,  and there is a success message for every command send from the web like absolute x move, but no movement at the stepper, any way to find out what exactly is happening,

**Comment by jokosup** [comment]
i am having the same issue as @mrmadhu. no movement at the stepper.

**Comment by ConnorRigby** [comment]
sorry guys my last comment got lost in transit I guess. 

Two things. 
1. Your Arduins need an update. The hardware is all working fine, the Arduino just doesn't have matching firmware. If you guys run Linux I can walk you thru updating them being that In the alpha release I gave you, the OTA updates are broken. 

2. The wifi issue is in fact power related. If it happens again you will need to source a good 5v 2.5 amp power supply.

**Comment by mrmadhu** [comment]
@ConnorRigby will get a linux Vbox, request you to please share the steps

**Comment by ConnorRigby** [comment]
ok. 
* install a ubuntu 16.04 image in vbox
* Make sure you can access your arduino from `inside` the vbox. 
* find the location of your arduino. (from a terminal you can run ` ls /dev/ttyACM0` or `ls /dev/ttyUSB0`)
   * it will probably be one of:
       * /dev/ttyACM0 
       * /dev/ttyUSB0
* run this inside a terminal: ` wget https://gist.githubusercontent.com/ConnorRigby/b8acfeb91d1c087680efeb489d9c926c/raw/c89db6f40e44fca484635007bf7b1733ecf7fd64/update.sh -qO- | bash -s `

**Comment by ConnorRigby** [comment]
@mrmadhu @jokosup 
I made a [beta release](https://github.com/FarmBot/farmbot_os/releases/tag/v2.0.7-beta) you can try instetad of the above steps.
 When your bot boots you should be able to hit that button and it will update your arduino. 
![screenshot from 2016-10-23 11-44-33](https://cloud.githubusercontent.com/assets/21150830/19628594/2ecbc49a-9916-11e6-8392-314371509c6f.png)

# NOTE
Do NOT hit the Controller Update button. It will actually make your bot go back to an older release. (because the image your using is beta)

**Comment by jokosup** [comment]
unable to update the Firmware, it seems stuck in updating FW

![screenshot from 2016-10-23 19-45-29](https://cloud.githubusercontent.com/assets/14942067/19630920/b403f324-9959-11e6-959f-7cf7eb011709.png)

**Comment by jokosup** [comment]
by the way, the stepper motor is now working. toggle switch tools (vacuum, water valve and led) are working as well. I only tested one motor as i only have 1 stepper motor driver right now (will have more tomorrow). Camera does not work, what should i put the value for camera's url?

**Comment by roryaronson** [comment]
@jokosup, the camera widget on the web app works with any webcam stream URL, but you have to setup a stream yourself. Right now the OS does not automatically stream the pi camera or a USB camera video, though that would be a nice feature! In the meantime if you set up something external, you can use that.

By the way, do you know the reason why the motors were not working for you before?

**Comment by mrmadhu** [comment]
still stuck with stepper motor issue, even after updating with new firmware. @ConnorRigby  - the new image that you have uploaded with arduino fix has wifi configuration issue again

**Comment by jokosup** [comment]
@roryaronson ok.  the new firmware fixed it. 

@mrmadhu try update the Arduino firmware with this command:
wget https://gist.githubusercontent.com/ConnorRigby/b8acfeb91d1c087680efeb489d9c926c/raw/c89db6f40e44fca484635007bf7b1733ecf7fd64/update.sh -qO- | bash -s
and also deploy the beta version of farmbot_os.

**Comment by ConnorRigby** [comment]
So the WiFi issue is power related actually. My latest beta image just shaves some power requirements off. You need at MINIMUM 2.5 amps from a 5 volt power supply. We will be shipping with a 3 amp psu.

**Comment by mrmadhu** [comment]
Perfect @ConnorRigby  all well with the new image, all works well with 2.1 amps, great job ....

**Comment by mrmadhu** [comment]
there are issues with web app, not sure if we need to put this into a new issue

**Comment by RickCarlino** [comment]
@mrmadhu Yes, please do. Preferably at the Repository for the frontend: https://github.com/FarmBot/farmbot-web-frontend

Thanks for all your help so far.

**Comment by ConnorRigby** [comment]
Thanks for your patience guys!

**Comment by ConnorRigby** [comment]
@mrmadhu Ah this is good news. Your arduino needs an update though and
github is down due to DNS errors i believe. (Github hosts our arduino
firmware releases)

@joko when you connect, you will loose wifi. (The raspberry pi can not
operate in wifi hotspot mode, and client mode at the same time) Does it
scan for networks? if you provided good credentials you will no longer see
FarmbotConfigurator.

**Comment by ConnorRigby** [comment]
Yes unfortunately your arduinos will need an update but if i remember
correctly the button to make them update is broken. If you guys run linux i
can walk you thru updating them from your normal pc

**Comment by jokosup** [comment]
@ConnorRigby i found that my router setting needs to be adjusted. the PSK is not enabled in my guest network.  

Do you make any updates on the staging site this morning, none of the features are working. BOT is connected, but when clicking any buttons or setting, it throwing an errors.

**Comment by ConnorRigby** [comment]
@jokosup  you probably need to reboot your bot.

**Comment by jokosup** [comment]
i have tried to reboot several times and still not working. 

![screenshot from 2016-10-25 21-46-57](https://cloud.githubusercontent.com/assets/14942067/19711642/c6e1a9b0-9afc-11e6-88d1-11d999b6d409.png)
