### ISSUE TITLE
Stuck on the random: nonblocking pool is initialized

### ISSUE THREAD

**Issue by jokosup** [FarmBot/farmbot_os#187]
try different SD-Cards and having same issues, work fine with NOOBS OS.

any suggestions?

**Comment by ConnorRigby** [comment]
That shoudlnt be an error its just a message from the kernel. How are you seeing that message? ftdi or HDMI? 

HDMI is currently not supported without recompiling the system
if it is over FTDI can you paste the full log?

**Comment by jokosup** [comment]
oh ok, i am seeing it when connecting it via HDMI. 

also, i don't see FarmbotConfigurator WiFi either.

**Comment by ConnorRigby** [comment]
your on a pi3 right? can you snap a picture of it via hdmi?

**Comment by jokosup** [comment]
yes, here's what i see in the screen via hdmi

![img_20161015_211831](https://cloud.githubusercontent.com/assets/14942067/19414774/f9de5c0a-931d-11e6-975c-dfee788589e2.jpg)

**Comment by ConnorRigby** [comment]
ok. So what are you powering your pi with? it looks like its not getting enough power to boot the Wifi Chip relialably

**Comment by jokosup** [comment]
powered from my laptop's usb, let me try to use dedicated power.
thanks for your quick response.

**Comment by ConnorRigby** [comment]
no problem. I have occasionally got this before but it goes away if i power it with something more powerful (something in the line of 2-2.5 amps) Im working on a fix so it should work at lower voltages more reliably

**Comment by jokosup** [comment]
yup, that's it.. it is working now. thanks. have a great weekend.
