### ISSUE TITLE
Trouble Connecting to Bot Version 3.0.4

### ISSUE THREAD

**Issue by Daniil145** [FarmBot/farmbot_os#247]
Version 3.0.4

Trouble connecting to bot

older versions normal connect and config

**Comment by ConnorRigby** [comment]
Have you tried rebooting your bot and refreshing the web application? Do you see a configurator wireless ssid?

**Comment by Daniil145** [comment]
Yes. Reboot+ wifi see connect go 192.168.24.1 downloading page and after one sec "Trouble connecting to bot" 3.0.3 work good

**Comment by ConnorRigby** [comment]
so version `3.0.3` works then?

**Comment by Daniil145** [comment]
last 3.0.3 work - clean install
3.0.4 work only update on api and dont work on clean install

**Comment by ConnorRigby** [comment]
interesting. checking it out right now! thanks

**Comment by ConnorRigby** [comment]
This should be fixed next release!

**Comment by ConnorRigby** [comment]
I lied. its still broken.

**Comment by ConnorRigby** [comment]
this was finally solved with a revert of the `tzdata` package.
