### ISSUE TITLE
I updated for farmbot-rpi3-3.0.8-rc.6.img and receive this error every time

### ISSUE THREAD

**Issue by Daniil145** [FarmBot/farmbot_os#272]
![401c7d80-0805-11e7-96fb-ef2b77aeea90](https://cloud.githubusercontent.com/assets/20598279/23867243/5b63c7fc-082c-11e7-8e83-26831be26fad.png)
API:0CB95F6 
FRONTEND:AA09142

**Comment by ConnorRigby** [comment]
Can you look on the Devices tab of the frontend, and tell me the `Controller Version`?

**Comment by Daniil145** [comment]
![123](https://cloud.githubusercontent.com/assets/20598279/23875761/9554258c-084b-11e7-86c9-35afc031e8ae.PNG)
Hmm I use Disk 32 imager and write flash

**Comment by ConnorRigby** [comment]
It appears you are still on an old version. For a quick fix to sequences, you can just hit the `SYNC` button then your sequences should be able to be run. 

i pushed a new update last night [herer](https://github.com/FarmBot/farmbot_os/releases/download/v3.0.8-rc.7/farmbot-rpi3-3.0.8-rc.7.fw) Could you try that one?
