### ISSUE TITLE
Steps per MM configuration is set back to default when flashing a new firmware

### ISSUE THREAD

**Issue by bdudout** [FarmBot/farmbot_os#275]
Hi everyone,

  * Farmbot OS version: 3.0.8 RC8 and before
  * Arduino Firmware version: same version

When I flash a new version of the firmware, my configuration settings are kept (speed, timeout, etc). But the steps per MM are set back to their default version (5 5 25)

#### Steps to reproduce:

  1. Change the steps per MM values and SYNC
  2. Flash a new version of the firmware on the SD card (or factory reset)
  3. Configure the frmbot with the same account, you should get back your configuration settings apart from the steps per MM

Do not hesitate to tell me if you need to test

Thanks

**Comment by ConnorRigby** [comment]
hello @bdudout sorry about that. Factory reset _*should*_  get rid of **ALL** configuration of the bot. Right now the current releases don't clear out the `arduino_firmware`. That is actually a bug and will be solved next release. 

some extra information: 
`steps_per_mm` is not actually stored in the firmware itself, it is a value stored on the farmbot's SD card so farmbot knows how to represent data to the user. So it makes sense that that will get cleared on factory reset.
