### ISSUE TITLE
End stops don't work on after new release

### ISSUE THREAD

**Issue by Daniil145** [FarmBot/farmbot_os#282]
my.farmbot.io
You disable endstops?

**Comment by ConnorRigby** [comment]
@Daniil145 sorry about that, they werent disabled, but there was a new version of teh Arduino Firmware released. 
Could you try disabling and re enabling end stops?

**Comment by Daniil145** [comment]
@ConnorRigby I dont understand "disabling and re enabling end stops" on interface dont have toggle off and on Endpoints. What can I do to activate them? With the loss of the Internet (especially when I use mobile Internet) the system behaves unpredictably. Especially this is critical for the Z axis. To do this, I need limit switches.

**Comment by ConnorRigby** [comment]
Oh sorry i didnt realize they werent on the interface any more. 
@RickCarlino any thoughts on this one?

**Comment by RickCarlino** [comment]
@Daniil145 I've recently added endstop toggle buttons to the device panel. They will be available in the next production release (probably this week).

**Comment by RickCarlino** [comment]
@Daniil145 We just did a production deploy. Please let us know if you find any issues.
