### ISSUE TITLE
raspberry pi

### ISSUE THREAD

**Issue by xiaoqingrong** [FarmBot/farmbot_os#302]
Will the farmbot_os system be installed on the raspberry pi? Because of the black screen。I don't know what I should do.

**Comment by RickCarlino** [comment]
@xiaoqingrong Have you tried to [configure the app over wifi](https://software.farmbot.io/v1.0/docs/wifi-configurator) ? If FarmBot OS installed properly, you should see a `farmbot-****` wifi network available.

**Comment by xiaoqingrong** [comment]
![qq 20170506192933](https://cloud.githubusercontent.com/assets/28303597/25771983/75842524-3292-11e7-82a6-c0c028ed0b00.png)
Thank you.No, I did it, right?

**Comment by xiaoqingrong** [comment]
The computer is always black.WIFI devices can be found in farmbot__xxx.Connect to the WIFI and open the web page at http://192.168.24.1/ and the computer displays the blue screen.I don't know what to do next

**Comment by ConnorRigby** [comment]
closing due to duplication. 
https://github.com/FarmBot/farmbot_os/issues/305
