### ISSUE TITLE
The system configuration

### ISSUE THREAD

**Issue by xiaoqingrong** [FarmBot/farmbot_os#305]
The computer is always black.WIFI devices can be found in farmbot__xxx.Connect to the WIFI and open the web page at http://192.168.24.1/ and the computer displays the blue screen.I don't know what to do next

**Comment by RickCarlino** [comment]
@xiaoqingrong Which browser are you using? We only support the latest version of Chrome and FIrefox at the moment.

Also, can you please show us a screen shot (or copy paste) the contents of the Javscript console?

You can access it on windows using `CTRL + SHIFT + J`.

**Comment by ConnorRigby** [comment]
Im having trouble understanding the issue.
When you get to the "blue screen" 
does it look like this?
![screenshot_2017-05-10_07-36-13](https://cloud.githubusercontent.com/assets/21150830/25904194/5f6ab104-3553-11e7-88f0-de7cdb76cd22.png)

If not could you take a screenshot of what you are seeing?

**Comment by ConnorRigby** [comment]
@xiaoqingrong not sure if there is still an issue. Please re-open if you have any problems.
