### ISSUE TITLE
Support for fixed IP address on the ethernet connection

### ISSUE THREAD

**Issue by kimptoc** [FarmBot/farmbot_os#313]
* Device: _____ Raspberry Pi
  * Farmbot OS version: _____ 3.1.6
  * Arduino Firmware version: _____ not sure - not done anything specific with this

NEW FEATURE - Trying to connect through corporate network to FarmBot.io - but need to give the Pi a fixed IP address so that the firewall can be opened up for it.

**Comment by ConnorRigby** [comment]
This is actually supported at the low level, we just need to expose a way for the user to set it up. Will look into it soon!

**Comment by ConnorRigby** [comment]
Sorry i forgot to update this. This was actually fixed in 6.4.1.
