### ISSUE TITLE
Tool verification read pin

### ISSUE THREAD

**Issue by Klimbim1** [FarmBot/farmbot_os#316]
To enable us to help you with the issue, please provide as much information as possible about your device and the problem. At a minimum, provide:
### Step 1: Are you in the right place?
This repository is for Farmbot OS problems.
I don't know if this should be covered here or in the web-api, please move if so...
### Step 2: Describe your environment

  * Device: what do you mean?
  * Farmbot OS version: 3.1.6
  * Arduino Firmware version: where can I read that?
### Step 3: Describe the problem:
If I execute this to read the tool verification pin:
![bildschirmfoto 2017-06-05 um 20 00 31](https://cloud.githubusercontent.com/assets/28235189/26796436/d1590b54-4a29-11e7-9c54-2cbeeefc9fa4.png)

It always says: ... set PIN: 63: 1, if I measure between B and C there is no 5V..., even during the execution of this sequence...

**Comment by RickCarlino** [comment]
This was fixed on a recent version of FarmBot OS that has not been released yet. Please check the releases page in a week or so.

**Comment by Klimbim1** [comment]
Does not work at the moment, it always says 1, regardless if I have a tool mounted (with installed jumper) or not... please give information on the best way to debug....
