### ISSUE TITLE
Max retries 

### ISSUE THREAD

**Issue by Klimbim1** [FarmBot/farmbot_os#334]
It seems that the max. retries setting is not saved permanently?
If I cycle power then this setting is again set to default (5)...

V. 4.0.1.

**Comment by ConnorRigby** [comment]
Very strange. Looking into right now.

**Comment by Klimbim1** [comment]
@ConnorRigby did you see anything whilst looking into "it" :D

**Comment by ConnorRigby** [comment]
@TimEvWw actually moved the implementation of this feature into the Arduino Firmware.
@gabrielburnworth and I are QA'ing it right now.
