### ISSUE TITLE
Reconnect after power cylce

### ISSUE THREAD

**Issue by Klimbim1** [FarmBot/farmbot_os#338]
As Rory is declining that the bot tries to reconnect to the WiFi after power recycle and mine does not
connect to the WiFi after power recycle, I open up this topic.
https://forum.farmbot.org/t/change-post-reboot-wifi-behaviour/2382/2

Please tell me how I can support you with more information. As always the log does not tell ma anything about that behaviour.

After the bot disconnects from the WiFi for whatever reason I power cycle it. Then I need to reconfigure it again, it wouldn`t connect to the WLAN automatically...

**Comment by ConnorRigby** [comment]
This issue is propagating down from #320 
Closing, and continuing discussion in that issue.
