### ISSUE TITLE
Can't ssh to device on 5.x

### ISSUE THREAD

**Issue by rootux** [FarmBot/farmbot_os#348]
I don't have the option to enable SSH on the initial configuration screen.
I've also tried putting the ssh file on the image and it did not work.

**Comment by rootux** [comment]
Version 5.0.2 (Latest) This is how my configuration screen looks like. No ssh.

<img width="722" alt="screen shot 2017-09-20 at 12 55 47 am" src="https://user-images.githubusercontent.com/1032526/30617433-b16b1710-9d9e-11e7-989f-0b8af9b6208c.png">

**Comment by ConnorRigby** [comment]
I've updated the [docs](https://github.com/FarmBot/farmbot_os/blob/master/docs/FAQ.md#can-i-ssh-into-the-farmbot). 

Basically FarmbotOS has no SSH because there are no usable Linux Utilities. (IE: `raspi-config`, `apt-get`, `sudo` etc)
