### ISSUE TITLE
Take Photo Fails On Raspberry pi Camera V2.1 on 5.0.2

### ISSUE THREAD

**Issue by rootux** [FarmBot/farmbot_os#349]
1.Connected the camera.
2.Set the Camera to `Raspberry Pi camera`.
3.Press on `Take photo`
3.Farmbot [take-photo] Problem getting image.

This is a new Farmbot image 5.0.2 (But it fails on an old image 5.0 after an upgrade)
Camera is version 2.1

**Comment by gabrielburnworth** [comment]
Have you tried rebooting?
The error message could also indicate that there's a ribbon cable connection issue.

**Comment by rootux** [comment]
I've tried rebooting several times. Will try again and tried to connect the ribbon cable 4 different places. will try again.
Have you tried working with the V2.1? Do you support this camera?

**Comment by rootux** [comment]
@gabrielburnworth OK weird now it looks like I get the cable connected right and I'm getting
Orange mark with - `Image Watcher trying to upload /tmp/images/1505859478.jpg~`

**Comment by rootux** [comment]
So it just does not show the image anywhere

<img width="831" alt="screen shot 2017-09-20 at 1 19 28 am" src="https://user-images.githubusercontent.com/1032526/30618136-c7af9d4a-9da1-11e7-8e35-c472357a54cf.png">

**Comment by gabrielburnworth** [comment]
Ah, that is a bug that has been fixed in the next FarmBot OS version, 5.0.3, which should be released this week. It looks like your camera is connected properly now, so after you upgrade it should work fine. Thanks for reporting the issue!

**Comment by gabrielburnworth** [comment]
FarmBot OS v5.0.3 has been released.
