### ISSUE TITLE
Image Watcher uploads everything twice

### ISSUE THREAD

**Issue by AscendFB** [FarmBot/farmbot_os#356]
Every image is uploaded twice, you can also see every picture duplicated in the panels.

Maybe this issue is even known, now we got it documented 😄 

![image](https://user-images.githubusercontent.com/23129562/31540794-e61099f6-b00c-11e7-9756-7215f9759de1.png)

**Comment by ConnorRigby** [comment]
Thanks for pointing this out! Working on a fix for this today

**Comment by ConnorRigby** [comment]
This is fixed as of Version 5.0.6.
