### ISSUE TITLE
cannot setup 6.0.0 

### ISSUE THREAD

**Issue by snzip** [FarmBot/farmbot_os#409]
START
FARMBOT UNEXPECTEDLY SHUT DOWN
Last shutdown reason: Failed to start child: Elixir.Farmbot.Firmware reason: enoent This is likely a bug. Please copy or screenshot this error and send it to the Farmbot developers.

environment: prod

source_ref: e43026a8af6a83878ead46210031987b54df11e6

target: rpi3

Stacktrace:

[	{Farmbot, :start, 2, [file: 'lib/farmbot.ex', line: 22]},

{:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 273]}]

Get ready to configure your FarmBot!

Network
Firmware
Web App Credentials

**Comment by ConnorRigby** [comment]
Can you tell me about your arduino? Is it a genuine Arduino or reproduction?

**Comment by ConnorRigby** [comment]
Also for the record - `6.0.1` is still a prerelease. 5.0.9 is the most recent production release.

**Comment by snzip** [comment]
yes, it's v6.0.1,   1.2. arduino

**Comment by ConnorRigby** [comment]
Can you take a photo of your Arduino?

**Comment by ConnorRigby** [comment]
Official 6.0.1 is out. Please repoen if you have any other issues

**Comment by snzip** [comment]
thanks

**Comment by rdegosse** [comment]
Hi, i have the same issue with 6.0.1 / 6.1.2 and my arduino is not genuine.
see: https://forum.farmbot.org/t/dont-config-6-0-1/3117
@ConnorRigby : do you think reproduction arduino can cause this issue?
thanks

**Comment by rdegosse** [comment]
issue solved with a new arduino, not genuine but not low cost!
