### ISSUE TITLE
Farmbot wifi network configurator address incorrect in docs

### ISSUE THREAD

**Issue by KizziePig** [FarmBot/farmbot_os#453]
Hi,
FYI:
In the docs at 
https://github.com/FarmBot/farmbot_os#floppy_disk-latest-os-image-downloads
it shows the configurator being http://192.168.25.1 but note that mine is at http://192.168.24.1 (the old address). I'm using version 6.01 (the latest available compiled release).

**Comment by gabrielburnworth** [comment]
Fixed. Thanks for pointing that out.

You can also visit the [software documentation Configurator page](https://software.farm.bot/docs/configurator) for more detailed configuration instructions.
