### ISSUE TITLE
Failed internet connection

### ISSUE THREAD

**Issue by birdontherun** [FarmBot/farmbot_os#573]
I'm running FarmBot V1.2. Since upgrading the OS to 6.4.3 the FarmBot cannot connect to the Internet.

**Comment by ConnorRigby** [comment]
Do you have any error messages? This is a very unspecific issue, and it sounds like you may have more help on [the forum](https://forum.farmbot.org/)
Feel free to re-open if you need, but GitHub Issues are usually used for developer issues.
