### ISSUE TITLE
Please consider vm.args : +C multi_time_warp 

### ISSUE THREAD

**Issue by jsimmonds2** [FarmBot/farmbot_os#640]
Hi !
Been having a head-scratching time trying to keep a little Process.send_after (monotonic {:abs, true}) in step with the OS time (which is now carefully NTP synchronized) . .  **Until** I noticed that the VM is started with the default `:no_time_warp` mode.

The ERTS guide to Time and Time Correction strongly encourages adopting the new API.  There wouldn't be old code still using erlang:now/0 _would there_ ?

**Comment by ConnorRigby** [comment]
This sounds like a great idea. I always use millisecond offsets in Farmbot code, but sub deps will need to be checked.

**Comment by ConnorRigby** [comment]
I'm testing this out today. It seems to be working alright. I'm going to do some QA and report back

**Comment by ConnorRigby** [comment]
This is staged to be released. :+1:  Thanks @jsimmonds2
