### ISSUE TITLE
3rd party farmware is gone after reboot 

### ISSUE THREAD

**Issue by etcipnja** [FarmBot/farmbot_os#680]
# Expected Behavior
Installed farmware is not removed after emergency reboot 

# Actual Behavior
My farmbot reboots itself quite often with the message UART device removed. After it boots all 3rd party firmware is gone and I have to reinstall it. Refreshing page doesn't help. However instead of reinstalling farmware I may initiate normal reboot and it brings my farmware back without reinstalling it

# Steps to Reproduce
I do not know how to provoke emergency reboot. 

# My FarmBot API Version
6.4.0

Run `git log -1` and paste the results here

**Comment by ConnorRigby** [comment]
I believe this was fixed quite a while ago. Feel free to reopen if you still have an issue
