### ISSUE TITLE
Latest 7.0.2-beta crashes early in boot :: esqlite3_nif.so

### ISSUE THREAD

**Issue by jsimmonds2** [FarmBot/farmbot_os#686]
Hoping to try out Elixir 1.8.1 and latest FarmBot OS bits so I grabbed the 3 day-old beta release from [https://github.com/FarmBot/farmbot_os/releases/download/v7.0.2-beta/farmbot-rpi3-7.0.2-beta.img](https://github.com/FarmBot/farmbot_os/releases/download/v7.0.2-beta/farmbot-rpi3-7.0.2-beta.img)

B.t.w. , where is the SHA256sum for released IMG files ?

This is as far as boot gets :

![image](https://user-images.githubusercontent.com/1224439/54483935-517b7480-48b0-11e9-8c7e-1ad444b97629.png)

**Comment by ConnorRigby** [comment]
Yeah this is a bug while upgrading to Elixir 1.8. It has to do with some incompatibilities with the `pc` rebar3 plugin and `elixir_make`

**Comment by ConnorRigby** [comment]
> B.t.w. , where is the SHA256sum for released IMG files

This is a good idea. I'll add it to our CI deployment

**Comment by ConnorRigby** [comment]
Should be fixed with https://github.com/FarmBot/farmbot_os/commit/c4407486a628b4aa768281a8a9324881a5bcfb15

**Comment by jsimmonds2** [comment]
Err, . .  nup.   Either that commit is not in the published `7.0.2-beta` IMG or it's no good.

Thanks for the SHA256sum !

I can wait 'til Eight  (v8.0.0) 👍

**Comment by ConnorRigby** [comment]
> I can wait 'til Eight (v8.0.0)

You and me both

Anyway the beta that came up had cached assets in it from CI. I busted the cache and it's rebuilding right now.

**Comment by jsimmonds2** [comment]
> Anyway the beta that came up had cached assets in it from CI. I busted the cache and it's rebuilding right now.

That's fixed it !   Thanks.
