### ISSUE TITLE
Minor typos in message and log record

### ISSUE THREAD

**Issue by jsimmonds2** [FarmBot/farmbot_os#702]
For v8.0.0 (currently `next` branch) in file `farmbot_os/lib/farmbot_os/sys_calls.ex` the word `frontend` is misspelled `frontent` :)

Also, in the device logs view at the WebApp side, we see this unusual grammatical (highlighted) :

![image](https://user-images.githubusercontent.com/1224439/56806714-0f126380-6870-11e9-8ae5-ef489235e52c.png)

**Comment by ConnorRigby** [comment]
Fixed. Thanks!
