### ISSUE TITLE
Provide Farmware name to Farmware executable

### ISSUE THREAD

**Issue by avonwyss** [FarmBot/farmbot_os#710]
The Farmware needs to know the name under which the configs can be retrieved (e.g. the prefix used in the environment values for config entries). This prefix (farmware name) could therefore also be made available in the environment, for instance as `FARMWARE_NAME`, in [lib/farmbot/farmware/runtime.ex](https://github.com/FarmBot/farmbot_os/blob/7ca4e5d936ff7ebbbbf2daa4d5755925e6394fd7/lib/farmbot/farmware/runtime.ex#L118)

**Comment by ConnorRigby** [comment]
The farmware name is hardcoded it the manifest.json file. If you want to know the name it dynamicly you could read this file and pull it from there

**Comment by avonwyss** [comment]
@ConnorRigby How can I read the manifest file used from within the Farmware?
