### ISSUE TITLE
v8.0.0 Configurator :: static IPv4 address bug

### ISSUE THREAD

**Issue by jsimmonds2** [FarmBot/farmbot_os#722]
As mentioned to @ConnorRigby in a FarmBot Forum PM, there's a simple bug which prevents legitimate `static` IPv4 address network configurations from being created.

Here's my `git diff` :

![image](https://user-images.githubusercontent.com/1224439/58551770-30da7e00-8254-11e9-94c7-e488afe6aa08.png)

**Comment by ConnorRigby** [comment]
Thanks for pointing this out. I'm actually in the process of helping get the top secret new nerves networking library https://github.com/nerves-networking/vintage_net ready for use. Which is why I haven't spent much time working on the network stack for v8 as it is rather temporary

**Comment by jsimmonds2** [comment]
Ok, thanks.  Last question : will the Configurator AP handling also change ?  (therefore, should I still hunt out the bug(s) in relevant current v8.0.0 code in `next` branch ?)

**Comment by ConnorRigby** [comment]
Yep AP handling will be moved into the same system.

**Comment by jsimmonds2** [comment]
Cool !   (and extra cool if **`static`** IPv4 adresses are supported in the official release too :)
(You and Frank are having way too much fun :):)

**Comment by ConnorRigby** [comment]
Should have been fixed in #760
