### ISSUE TITLE
v8.0.0 Log message :: grammar (?)

### ISSUE THREAD

**Issue by jsimmonds2** [FarmBot/farmbot_os#734]
It's "the pesky proof-reader" here again :)

![Screenshot from 2019-06-05 18-37-54](https://user-images.githubusercontent.com/1224439/58942837-deeca780-87c1-11e9-8d9a-5b7c68e0901b.png)

**Comment by ConnorRigby** [comment]
Fixed in #779 by deleting that log message entirely :)
