### ISSUE TITLE
Pre-release :: busybox dep. issue in v8.0.0-rc0 / staging

### ISSUE THREAD

**Issue by jsimmonds2** [FarmBot/farmbot_os#762]
Sorry for this bit of silly noise, but just wanted to make sure I can build this version before grabbing the pre-built artefact IMG file.

Building inside a fresh clone.

![Screenshot from 2019-07-02 16-40-44](https://user-images.githubusercontent.com/1224439/60490050-22ff9900-9ce9-11e9-85ba-bfcff585dc08.png)

**Comment by ConnorRigby** [comment]
Did you try cleaning and rebuilding? It looks like the download was corrupted

**Comment by jsimmonds2** [comment]
Well, I haven't yet because I saw that the hash compare failed on **`busybox-1.30.1.tar.bz2`** and not the version that Frank has kindly provided :)
P.s. surely a corrupt download would be detected way earlier ?

**Comment by jsimmonds2** [comment]
Did another clean clone (of v8.0.0-rc1 this time) and get same failure in `mix firmware` stage.
Can't see how my (very simple) environment could be a cause . . I've tried both `MIX_ENV=dev` and `MIX_ENV=prod`

![Screenshot from 2019-07-03 11-33-20](https://user-images.githubusercontent.com/1224439/60556859-6f4ce680-9d86-11e9-9ef3-3e7971f6b342.png)

**Comment by ConnorRigby** [comment]
Can you open an issue on nerves-networking/elixir_busybox

**Comment by jsimmonds2** [comment]
Of course . . thanks :)

**Comment by fhunleth** [comment]
@jsimmonds2 Thanks for the report and for filing a bug over at the `elixir_busybox` repo.

@ConnorRigby `busybox` is an optional dependency. I was thinking that you wouldn't need it for farmbot_os since you'd be enabling the required busybox packages in your custom systems. (Not that this fixes any issue with `elixir_busybox`, that is...)

**Comment by ConnorRigby** [comment]
Yeah I'm only using the Elixir BusyBox dep for now to save me time building systems as I have 3 custom ones that take quite a while to build/release. I will switch back at some point in the near future.

Also figured I'd stress test the new BusyBox package :troll:

**Comment by jsimmonds2** [comment]
@fhunleth  thanks so much for your ever-so-patient encouragement !

Removing that `:busybox` dep from `farmbot_os` `v8.0.0-rc18` gives me a clean build :+1:  Yay.
(B.t.w. that dep. isn't flagged `optional` in the `farmbot_os` config _ :puzzled: )

Now I can go sleuthing the issue that's causing `:nerves_runtime :stopped` in this pre-release version !

**Comment by jsimmonds2** [comment]
For the record, here's a snip of the RingLogger log showing `:nerves_runtime` stopping.

![Screenshot from 2019-07-09 17-45-19](https://user-images.githubusercontent.com/1224439/60869075-a4b76f80-a271-11e9-880c-f245031a4997.png)
