### ISSUE TITLE
[Farmware] Farmware-Tools install/update after OTA

### ISSUE THREAD

**Issue by ConnorRigby** [FarmBot/farmbot_os#786]
If a Farmware that needs farmware tools is installed on an old OS version before farmware tools, it will error (farmware tools not found, etc.).

To run the Farmware successfully, the OS needs to be updated to a version after farmware tools was released. However, after the upgrade farmware tools is still not installed for the Farmware, so it needs to be uninstalled and then reinstalled.

**Comment by gabrielburnworth** [comment]
Farmware in FarmBot OS v8 are freshly installed with Farmware Tools to `/tmp`, which fixes this issue.
