### ISSUE TITLE
[BotState] Track `last_updated` and `last_checked` for OTA updates 

### ISSUE THREAD

**Issue by ConnorRigby** [FarmBot/farmbot_os#789]
add new fields to `informational_settings`: 
* `last_ota_update` - unix date time
* `last_ota_checkup` - unix date time

**Comment by ConnorRigby** [comment]
Fixed in https://github.com/FarmBot/farmbot_os/commit/2f36e2d564aea60cd39d24466da3810dbfddd198

**Comment by roryaronson** [comment]
From @ConnorRigby: "farmbot goes offline to reboot before [`last_ota_update`] gets synced"

Moving through the project board for now
