### ISSUE TITLE
[Sequence] Execute a sequence on boot

### ISSUE THREAD

**Issue by ConnorRigby** [FarmBot/farmbot_os#792]
This would be a nice feature, and may be useful for `home on boot` type situations

**Comment by RickCarlino** [comment]
IDEA BIN: We could add this to the device table to ensure referential integrity, prevent user from accidentally deleting their boot sequence, etc...

**Comment by jsimmonds2** [comment]
There is a "User Disappointer" bug in the solution submitted in [PR#1487](https://github.com/FarmBot/farmbot_os/pull/1487)

Any User's valid and pre-existing `Boot Sequence` will fail to run ( once ), immediately after an **`FBOS Soft Reset`** ( a.k.a. Factory Reset ) with a failure like this ( ignore the Erlang OOM . . seems something to do with the `log_attach` done earlier )

![Screenshot 2022-04-03 175228](https://user-images.githubusercontent.com/1224439/162427043-3eb7e748-9543-4af5-a9f5-1602ad42c6c5.jpg)

As is evident, **`Auto Sync`** takes longer on **_first boot_** after a `Soft Reset` than it normally would.

I will have a code fix PR ready in next few days.
