### ISSUE TITLE
[Farmware] Add optional `min_os_version_minor` to manifest

### ISSUE THREAD

**Issue by ConnorRigby** [FarmBot/farmbot_os#801]
to allow updates to versions with new features from old OSes to fail (in the future, this would have been very helpful in the case of farmware tools)

**Comment by gabrielburnworth** [comment]
Fixed via `farmbot_os_version_requirement` in https://github.com/FarmBot/farmbot_os/commit/fff4963f7e787fef35a7a53b602d4a7e4f0dd214.
