### ISSUE TITLE
[Farmware] Support multiple manifest args

### ISSUE THREAD

**Issue by gabrielburnworth** [FarmBot/farmbot_os#838]
# FarmBot OS version
`8.0.0-rc26`

# Relevant code
https://github.com/FarmBot/farmbot_os/blob/3b118dade466f785bc94c7751c311fcc3dab01c0/farmbot_core/lib/farmbot_core/farmware_runtime.ex#L115

Since the Farmware manifest `args` field is now a string instead of an array, the above line allows single args (such as `"run.py"`) to work. To support multiple args in the string (such as `"run.py -n 1"`), a different approach must be used.

**Comment by ConnorRigby** [comment]
```json
{
 "package": "arg test",
 "language": "sh",
 "author": "FarmBot, Inc.",
 "description": "test",
 "farmware_manifest_version": "2.0.0",
 "package_version": "0.0.0",
 "farmbot_os_version_requirement": ">=0.0.0",
 "farmware_tools_version_requirement": ">=0.0.0",
 "url": "",
 "zip": "https://github.com/FarmBot-Labs/farmware_manifests/archive/master.zip",
 "executable": "sh",
 "args": "-c 'echo hello'"
}
```
