### ISSUE TITLE
FBOS may be over-using sync endpoint

### ISSUE THREAD

**Issue by RickCarlino** [FarmBot/farmbot_os#855]
I have anecdotally noticed an increase in 429 responses from the API while using v8, often when accessing the `/sync` endpoint. 

The `/sync` endpoint has a lower threshold for throttling (for performance reasons), so it is likely the cause.

TODO:

 - [ ] Reproduce the issue locally on FarmBot Jr.
 - [ ] Identify root cause
 - [ ] Apply fix as needed

**Comment by ConnorRigby** [comment]
@RickCarlino have you had a chance to look at this? 429 is expected behaviour in case farmbot gets stuck in a feedback loop if there was an error. I suspect you were just on a release with a firmware sync related bug. Feel free to re-open if you can reproduce
