### ISSUE TITLE
[Farmware] implement update_farmware

### ISSUE THREAD

**Issue by gabrielburnworth** [FarmBot/farmbot_os#896]

**Comment by ConnorRigby** [comment]
Do we have a road map for this one? I believe we removed the `update_farmware` rpc, but it can be added back pretty easily. The other option is to have the API dispatch the sync message which i believe would cause it to update

**Comment by gabrielburnworth** [comment]
I'm not sure, but the `update_farmware` RPC is used throughout the rest of the stack. If we wanted the API to send the command via a message instead, there would need to be a few changes in the App (since the installation data doesn't change during an update).
