### ISSUE TITLE
[CeleryScript] Implement `set_pin_io_mode`

### ISSUE THREAD

**Issue by gabrielburnworth** [FarmBot/farmbot_os#897]
# FarmBot OS Version
`8.0.0-rc53`

# Previous implementation
https://github.com/FarmBot/farmbot_os/blob/1fe52021c71bfe068c2be09bd8ded99c211804f6/lib/farmbot/firmware/uart_handler/uart_handler.ex#L384-L387

https://github.com/FarmBot/farmbot_os/blob/1fe52021c71bfe068c2be09bd8ded99c211804f6/lib/farmbot/firmware/utils.ex#L27-L29

**Comment by ConnorRigby** [comment]
Is `set_pin_mode` ever used? is it an RPC? I didn't add it to V8 because i couldn't find any usage of it.

**Comment by ConnorRigby** [comment]
Just kidding i found the old RPC. Reimplementing

**Comment by gabrielburnworth** [comment]
errors:
```
function FarmbotCeleryScript.SysCalls.set_pin_io_mode/2 is undefined or private
```
```
no function clause matching in FarmbotOS.SysCalls.SetPinIOMode.extract_set_pin_mode/1
```
```
STUB HANDLER: unknown code: {"32", {:pin_mode_write, [p: 13, m: 0]}}
```
Here is the implementation used in production:
```JSON
{
    "kind": "set_pin_io_mode",
    "args": {
        "pin_number": 13,
        "pin_io_mode": 0
    }
}
```

https://github.com/FarmBot/farmbot_os/blob/1fe52021c71bfe068c2be09bd8ded99c211804f6/lib/farmbot/celery_script/ast/arg/pin_io_mode.ex#L1-L12
