### ISSUE TITLE
[Firmware] Firmware initializes to "none" on boot

### ISSUE THREAD

**Issue by gabrielburnworth** [FarmBot/farmbot_os#898]
# FarmBot OS Version
`8.0.0-rc53`

# To reproduce
Reboot or power cycle a device attached to an account with a firmware selected and working.

# Temporary workaround
Selecting a different firmware flashes it, at which point the desired firmware can be selected and flashed.

# See also
https://forum.farmbot.org/t/using-farmbotos-beta-updates/3951/42

**Comment by jsimmonds2** [comment]
Thanks.  Also, that little button on the pop-up doesn't fix things in this situation.
