### ISSUE TITLE
[Farmware] FarmwareEnvs not updating

### ISSUE THREAD

**Issue by gabrielburnworth** [FarmBot/farmbot_os#913]
# FarmBot OS version
`8.0.0-rc56`

# Expected

FarmBot OS should create and update `FarmwareEnvs` in the Web App upon `set_user_env`.

# To reproduce

`FarmbotOS.SysCalls.set_user_env`. `FarmbotCore.Asset.new_farmware_env` is used below to provide more info. (Perhaps error status should be passed through?)

Create:
```elixir
> FarmbotCore.Asset.new_farmware_env(%{key: "key0", value: "0"})
{:ok, %FarmbotCore.Asset.FarmwareEnv{key: "key0", value: "0", ...}}
```
This works; the key/value shows up in the Web App `FarmwareEnv` and bot state.

Attempt to update:
```elixir
> FarmbotCore.Asset.new_farmware_env(%{key: "key0", value: "1"})
{:ok, %FarmbotCore.Asset.FarmwareEnv{key: "key0", value: "1", ...}}
```
FarmBot OS updates the value in the bot state but does not update the value in the Web App `FarmwareEnv`.

Also, creating or updating values of integer type does not work:
```elixir
> FarmbotCore.Asset.new_farmware_env(%{key: "key1", value: 1})
{:error,
 #Ecto.Changeset<
   action: :insert,
   changes: %{key: "key1"},
   errors: [value: {"is invalid", [type: :string, validation: :cast]}],
   data: #FarmbotCore.Asset.FarmwareEnv<>,
   valid?: false
 >}
```

# Relevant code
https://github.com/FarmBot/farmbot_os/blob/b93c31ae3b5eaee42824de45a10297935b7c5def/farmbot_os/lib/farmbot_os/sys_calls.ex#L128-L131
https://github.com/FarmBot/farmbot_os/blob/b93c31ae3b5eaee42824de45a10297935b7c5def/farmbot_core/lib/farmbot_core/asset.ex#L376-L386
https://github.com/FarmBot/farmbot_os/blob/b93c31ae3b5eaee42824de45a10297935b7c5def/farmbot_core/lib/farmbot_core/asset/farmware_env.ex#L7-L20

**Comment by ConnorRigby** [comment]
> Also, creating or updating values of integer type does not work:

This is intended. Since `FarmwareEnv` must be serialized to a string when passing to a farmware, data must be supplied as a string.
