### ISSUE TITLE
[Farmware] honor all Farmware requests

### ISSUE THREAD

**Issue by gabrielburnworth** [FarmBot/farmbot_os#919]
# FarmBot OS version
`8.0.0-rc57`

# Expected
FarmBot OS handles all requests given by a Farmware.

# Experienced
FarmBot OS buffers requests and ignores those left in the buffer after the Farmware exits.

# Possible solution
Work through the request buffer after a Farmware exits.

**Comment by ConnorRigby** [comment]
I believe this was fixed when we switched from named_pipes to domain sockets. Feel free to reopen if it's still a problem
