### ISSUE TITLE
[CI/CD] Release package also contains earlier Release artefacts

### ISSUE THREAD

**Issue by jsimmonds2** [FarmBot/farmbot_os#975]
As noted in [this FarmBot Forum post](https://forum.farmbot.org/t/using-farmbotos-beta-updates/3951/63), September 13 edit.

**Comment by jsimmonds2** [comment]
Hello @ConnorRigby . . this issue has re-occurred :|   ( maybe only a 'Pre-Release' thing ? )

![image](https://user-images.githubusercontent.com/1224439/65558933-f2dc3500-df7b-11e9-85a8-4509ac8eeaf1.png)

**Comment by ConnorRigby** [comment]
Yes release candidate images will contain old versions due to caching. Production releases should not
