### ISSUE TITLE
Sequence get stuck after `Execute Farmware` step

### ISSUE THREAD

**Issue by AscendFB** [FarmBot/farmbot_os#994]
# FarmBot OS version
 `8.0.2`
 
 # Behavior
Sequences that contain an `EXECUTE FARMWARE` always get stuck after the farmware execution. All the steps that should be run after the farmware simply don't get processed. A little more information and steps to reproduce [in this forum post](https://forum.farmbot.org/t/powerloop-not-workig-in-v8-0-0-anymore/5470/2)
 
 # Expected
Also run the steps behind the farmware call, commonly used for homing or tool handling after looping farmwares.

**Comment by ConnorRigby** [comment]
Fixed in #999
